### PR TITLE
Kitchen

### PR DESCRIPTION
**Pull request by tigpas**
Hi,

I added a basic kitchen file for testing.

It needed some pkgs for Debian, so I added it, too.

Regards

Pascal

### CODE REVIEW

**Comment by aboe76** [comment]
@tigpas You might take a look at how the template-formula is using kitchen salt testing.
It's more work but afterwards easier to maintain.

**Comment by tigpas** [comment]
I will try to understand the structure and implement it. But if anyone is faster, feel free ;-)

**Comment by 7meis** [comment]
@myii, would it be possible to merge this PR? Thank you.

**Comment by baby-gnu** [comment]
As this project has no CI, I agree to merge it as-is because it's requested.

**Comment by 7meis** [comment]
thank you @baby-gnu! 💪

**Pull request merged**
